name: Build Adoptium Image

on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - "Adoptium/**"
  pull_request:
    branches:
    - master
    paths:
    - "Adoptium/**"

permissions:
  contents: write
  pull-requests: write 
  issues: read
  packages: write

jobs:
  build:
    name: "Build Adoptium ${{ matrix.tag }} Image"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag:
          - 8
          - 11
          - 17
          - 19
          - 21
          - 20
          - 22
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta_adoptium
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/adoptium
          tags: |
            ${{ matrix.tag }}
            
      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Adoptium/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_adoptium.outputs.tags }}
          labels: ${{ steps.meta_adoptium.outputs.labels }}
          build-args: |
            "GITHUB_USER=${{ github.repository_owner }}"
